name: Create working Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Установка .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Сборка проекта
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o out

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка Docker image
        run: |
          docker build --no-cache -t egorixa08/dockernis .
          docker push egorixa08/dockernis
          
      - name: Проверка, что образ собран
        run: docker images | grep dockernis
